[tool.poetry]
name = "testcasetornado"
version = "0.1.0"
description = ""
authors = ["sivaplaysmC <sivaram.asdf@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
multipart = "^0.2.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
